### ISSUE TITLE
Build fail with newest llvm

### ISSUE THREAD

**Issue by iamsergio** [a-richardson/convert2qt5signalslot#35]
Build fails with latest LLVM:

/data/prefix/include/llvm/Support/DataTypes.h:57:3: error: "Must #define __STDC_LIMIT_MACROS before #including Support/DataTypes.h"

**Comment by iamsergio** [comment]
I now get:

In file included from /data/sources/convert2qt5signalslot/Qt5SignalSlotSyntaxConverter.cpp:2:
/data/sources/convert2qt5signalslot/PreProcessorCallback.h:38:85: error: non-virtual member function marked 'override' hides virtual member function
    void MacroUndefined(const clang::Token& token, const clang::MacroDirective* md) override {
                                                                                    ^
/data/prefix/clang-3.7/include/clang/Lex/PPCallbacks.h:254:16: note: hidden overloaded virtual function 'clang::PPCallbacks::MacroUndefined' declared here: type mismatch at 2nd parameter
      ('const clang::MacroDefinition &' vs 'const clang::MacroDirective *')
  virtual void MacroUndefined(const Token &MacroNameTok,
               ^
Looks like there was a signature change

**Comment by iamsergio** [comment]
almost :)

https://paste.kde.org/pnj36qz46

**Comment by a-richardson** [comment]
How are you building LLVM/clang? Is it by any chance using static libs?

I am using a build with -DBUILD_SHARED_LIBS=ON (same for the packages built on OBS with 3.5 and 3.6.1) so I guess those get the library dependencies right somehow.

I will try a static build and see exactly which libraries are required.

**Comment by iamsergio** [comment]
Yes, it's using static libs
